#! /bin/sh

killall picom
picom --corner-radius 15 &
nitrogen --restore &
~/.config/polybar/launch.bspwm.sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 M

bspc config border_width         2
bspc config window_gap          20

bspc config top_padding         25
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^6'
